#include "FFmpegProcess.h"

#include <QProcess>

/*
 * Constructor
 *
 * Creates the QProcess object.
 */
FFmpegProcess::FFmpegProcess(QObject *parent)
    : QObject(parent)
{
    m_process = new QProcess(this);

    /*
     * FFmpeg writes information to stderr.
     *
     * We connect readyReadStandardError() so we can receive
     * FFmpeg's messages without blocking the GUI.
     */
    connect(m_process, &QProcess::readyReadStandardError,
            this, [this]()
    {
        const QString output =
            QString::fromLocal8Bit(m_process->readAllStandardError());

        emit outputReceived(output);
    });

    /*
     * QProcess tells us when the external program has finished.
     */
    connect(m_process,
            QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
            this,
            [this](int /*exitCode*/, QProcess::ExitStatus /*exitStatus*/)
    {
        emit stopped();
    });

    /*
     * Handle errors such as:
     *
     * - FFmpeg executable not found
     * - Permission denied
     * - Unable to open /dev/videoX
     */
    connect(m_process,
            &QProcess::errorOccurred,
            this,
            [this](QProcess::ProcessError error)
    {
        QString message;

        switch (error)
        {
        case QProcess::FailedToStart:
            message = "FFmpeg failed to start.";
            break;

        case QProcess::Crashed:
            message = "FFmpeg crashed.";
            break;

        case QProcess::Timedout:
            message = "FFmpeg operation timed out.";
            break;

        case QProcess::WriteError:
            message = "Error writing to FFmpeg.";
            break;

        case QProcess::ReadError:
            message = "Error reading FFmpeg output.";
            break;

        default:
            message = "Unknown FFmpeg process error.";
            break;
        }

        emit errorOccurred(message);
    });
}


/*
 * Start FFmpeg.
 *
 * Example command generated by this function:
 *
 * ffmpeg
 *   -nostdin
 *   -re
 *   -stream_loop -1
 *   -i /home/user/video.mp4
 *   -vf scale=1280:720,format=yuv420p
 *   -pix_fmt yuv420p
 *   -f v4l2
 *   /dev/video0
 */
void FFmpegProcess::start(const QString &videoPath,
                          const QString &devicePath)
{
    /*
     * If FFmpeg is already running, stop it first.
     *
     * This is important when the user switches from one video
     * to another.
     */
    if (isRunning())
    {
        stop();
    }

    /*
     * Build the FFmpeg argument list.
     *
     * Using QStringList is safer than manually creating one
     * giant command string.
     */
    QStringList arguments;

    // Do not allow FFmpeg to wait for keyboard input.
    arguments << "-nostdin";

    // Read the video at its normal playback speed.
    arguments << "-re";

    // Repeat the video forever.
    arguments << "-stream_loop" << "-1";

    // Input video.
    arguments << "-i" << videoPath;

    /*
     * Resize the video to the format expected by our virtual camera.
     *
     * 1280x720 = HD 720p
     * yuv420p  = common camera-compatible pixel format
     */
    arguments << "-vf"
              << "scale=1280:720,format=yuv420p";

    // Explicit output pixel format.
    arguments << "-pix_fmt" << "yuv420p";

    // Tell FFmpeg that the output is a V4L2 device.
    arguments << "-f" << "v4l2";

    // The automatically detected virtual camera.
    arguments << devicePath;

    /*
     * Start the actual FFmpeg process.
     */
    m_process->start("ffmpeg", arguments);

    /*
     * Wait a very short amount of time to see whether the
     * process could actually start.
     *
     * This does NOT block for the video itself.
     */
    if (!m_process->waitForStarted(1000))
    {
        emit errorOccurred(
            "Could not start FFmpeg. Make sure FFmpeg is installed."
        );

        return;
    }

    emit started();
}


/*
 * Stop FFmpeg.
 */
void FFmpegProcess::stop()
{
    if (!isRunning())
        return;

    /*
     * Ask FFmpeg to terminate normally.
     */
    m_process->terminate();

    /*
     * Give FFmpeg a little time to shut down.
     */
    if (!m_process->waitForFinished(1500))
    {
        /*
         * If FFmpeg refuses to stop, force it.
         */
        m_process->kill();
        m_process->waitForFinished(500);
    }

    emit stopped();
}


/*
 * Return whether FFmpeg is currently running.
 */
bool FFmpegProcess::isRunning() const
{
    return m_process->state() != QProcess::NotRunning;
}